import { HttpException, HttpStatus, Injectable } from '@nestjs/common';
import { User } from '../user/entities/user.entity';
import { ApplicationService } from '../application/application.service';
import { LoginDto } from './dto/login.dto';

@Injectable()
export class AuthService {

    constructor(){}
    async login(user : User , password : string){
        console.log(user.password)
        if(user.password === password){
            const jwt = require('jsonwebtoken'); 
            const secret = "3GKsOqRULgOicqaAgzPWGO"
            const token = jwt.sign({
                "sub": "1BLhVLF4hei6fAH0atBgYn", //keyId generated by eg create
                "user_name": user.user_name,
                "refrence_number": user.refrence_number,
                "iat": 1538828706
            },secret);
            return token
        }
        else{
            throw new HttpException({
                message : "Invalid Password"
            },HttpStatus.UNAUTHORIZED)
        }
    }
}
